id: IF3FBBE8F
legacy_id: P006822
ocr_import_info:
  bdrc_scan_id: W15960
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T11:46:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:51:47.373620+00:00'
last_modified: 2022-08-30 22:52:12.103440
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W15960
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW15960
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབྱངས་ཅན་གྲུབ་པའི་རྡོ་རྗེའི་རྣམ་ཐར།
  author: དངུལ་ཆུ་བློ་བཟང་འཇིགས་མེད་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6747665654716721
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I6459:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6459
      total_pages: 420
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6459.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6747665654716721
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
